name: Build TypeScript

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Check out repository
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Versi Node.js yang kamu gunakan

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Compile TypeScript to JavaScript
      - name: Compile TypeScript
        run: npx tsc

      # Optionally, you can deploy or do further steps after the build